import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./glonalStyles/normalize.css";
import "./glonalStyles/globals.css";
import "./glonalStyles/header.css";
import './glonalStyles/menu.css'
import './glonalStyles/mobile-navbar.css'
import './glonalStyles/catalog-menu.css'
import Layout from "./components/layouts/layout";





const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopping Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
        </body>
    </html>
  );
}
