import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PagesLatout from "./components/layouts/PagesLayout"
import "./glonalStyles/normalize.css";
import "./glonalStyles/globals.css";
import "./glonalStyles/header.css";
import './glonalStyles/menu.css'
import './glonalStyles/mobile-navbar.css'
import './glonalStyles/catalog-menu.css'
import './glonalStyles/search-modal.css'
import './glonalStyles/footer.css'
import './glonalStyles/auth-popup.css'






const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopping Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PagesLatout>{children}</PagesLatout>
        </body>
    </html>
  );
}
